apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: autoregex-telegram-bot-token
  namespace: telegram-bot
spec:
  encryptedData:
    TOKEN: AgCbu+2MezneJbKLj1W+Kk0uXhru40G09ackNPtLlWBCXbRAq/5XzoJWIMrMFBoxtmNIkpg4zXETESNTcu2TI7s5ANVrjYofjOjJMSNYabrB8eC/9USSmZgsel5M+lFNK+3dGlEG6YYhDojRp3cUgRUP3c1fw4/K2Bsp46wSeVkVXtZDpkMFBagPAmhkPCycTQQXDQ3g9YDI9USBS/tCmW5OixDoeMIp8h9shwiN5Hmr0v/LihGVO+mQjvbM8tR+wQSZQIoAOungQZtGd9ss1tFsB9MOFoyHXhhsjdgERLN+9Ib8x9E/EElepbHCLcltQKLxiYybsmYGgmaLyHQOPReAxYCNIDpjVINefWPgTOa40wz0it7Us79ej+30i47JyVkzcIW8PR47xqqVHWt1ar+7BuCkow/RJyhiwkw4c16QDCcNdylNvjNQy7R+Tnb2DZhrBaILZd+4mTVo7doqyOc8cAgt1iw9oTcaLkp4bebfJv7wgjJSP414NUdtonNiVfbVl5kiYFllPLmZetng63cAZgJADrHrAAGfK0hzXjg4nEXV4nJxp+Pw5P7wcUIAniEI6tTDCc2sYx/ioWY+igt0SBmyxfrg0WTThalNSwNZ2SG0RiV7tQ9ZyfiW02hp5piilmGg1Bsj7znRPu9gzmuMf62oV9KK4alPF8F6ZDThPZ3EWbS+NiyGS/HehjWrl6vHh7YFIhR9wuFPoMj5kVOJRLaL+3In/U9vSim0jPelGXXxJKm9SNjwgXZlCzYC
  template:
    metadata:
      name: autoregex-telegram-bot-token
      namespace: telegram-bot
    type: Opaque
